# Generated by ChatGPT: add telemetry fields to DeviceInstance
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_deviceinstance_claimed_at_deviceinstance_claimed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstance',
            name='last_wifi_event',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='last_rssi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='last_disconnect_reason',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='server_reachable',
            field=models.BooleanField(default=False),
        ),
    ]
