from django.urls import path

from .views import (
    BorrowCreateView,
    ReturnView,
    BorrowerView,
    BorrowerDetailView,
    ItemView,
    ItemDetailView,
    BorrowTransactionDetailView,
    ScanIdView,
    BorrowerRegistrationView,
    ItemRegistrationView,
    ItemQRCodeView,
    RFIDScanView,
    DeviceConfigView,
    DeviceInstanceView,
    ScanDevicesView,
    ClaimDeviceView,
    DeviceInstanceTokenView,
    PushDeviceConfigView,
    DeviceInstanceDetailView,
    ProvisionDeviceView,
    DeviceControlView,
    PushDeviceConfigAllView,
    TestApiHostView,
    PingView,
)


urlpatterns = [
    path("borrow", BorrowCreateView.as_view(), name="api-borrow"),
    path("borrow/", BorrowCreateView.as_view(), name="api-borrow-slash"),
    path("return", ReturnView.as_view(), name="api-return"),
    path("return/", ReturnView.as_view(), name="api-return-slash"),
    path("borrowers", BorrowerView.as_view(), name="api-borrowers"),
    path("borrowers/", BorrowerView.as_view(), name="api-borrowers-slash"),
    path("borrowers/<int:borrower_id>", BorrowerDetailView.as_view(), name="api-borrowers-detail"),
    path("borrowers/<int:borrower_id>/", BorrowerDetailView.as_view(), name="api-borrowers-detail-slash"),
    path("items", ItemView.as_view(), name="api-items"),
    path("items/", ItemView.as_view(), name="api-items-slash"),
    path("items/<int:item_id>", ItemDetailView.as_view(), name="api-items-detail"),
    path("items/<int:item_id>/", ItemDetailView.as_view(), name="api-items-detail-slash"),
    path("transactions/<int:transaction_id>", BorrowTransactionDetailView.as_view(), name="api-transactions-detail"),
    path("transactions/<int:transaction_id>/", BorrowTransactionDetailView.as_view(), name="api-transactions-detail-slash"),
    path("scan-id", ScanIdView.as_view(), name="api-scan-id"),
    path("scan-id/", ScanIdView.as_view(), name="api-scan-id-slash"),
    path("register-borrower", BorrowerRegistrationView.as_view(), name="api-register-borrower"),
    path("register-borrower/", BorrowerRegistrationView.as_view(), name="api-register-borrower-slash"),
    path("register-item", ItemRegistrationView.as_view(), name="api-register-item"),
    path("register-item/", ItemRegistrationView.as_view(), name="api-register-item-slash"),
    path("items/<int:item_id>/qr", ItemQRCodeView.as_view(), name="api-item-qr"),
    path("items/<int:item_id>/qr/", ItemQRCodeView.as_view(), name="api-item-qr-slash"),
    path("rfid-scans", RFIDScanView.as_view(), name="api-rfid-scans"),
    path("rfid-scans/", RFIDScanView.as_view(), name="api-rfid-scans-slash"),
    path("device-config", DeviceConfigView.as_view(), name="api-device-config"),
    path("device-config/", DeviceConfigView.as_view(), name="api-device-config-slash"),
    path("device-instances", DeviceInstanceView.as_view(), name="api-device-instances"),
    path("device-instances/", DeviceInstanceView.as_view(), name="api-device-instances-slash"),
    path("device-instances/scan", ScanDevicesView.as_view(), name="api-device-instances-scan"),
    path("device-instances/scan/", ScanDevicesView.as_view(), name="api-device-instances-scan-slash"),
    path("device-instances/claim", ClaimDeviceView.as_view(), name="api-device-instance-claim"),
    path("device-instances/claim/", ClaimDeviceView.as_view(), name="api-device-instance-claim-slash"),
    path("device-instances/token", DeviceInstanceTokenView.as_view(), name="api-device-instance-token"),
    path("device-instances/token/", DeviceInstanceTokenView.as_view(), name="api-device-instance-token-slash"),
    path("device-instances/push-config", PushDeviceConfigView.as_view(), name="api-device-instance-push-config"),
    path("device-instances/push-config/", PushDeviceConfigView.as_view(), name="api-device-instance-push-config-slash"),
    path("device-instances/<int:device_id>", DeviceInstanceDetailView.as_view(), name="api-device-instance-detail"),
    path("device-instances/<int:device_id>/", DeviceInstanceDetailView.as_view(), name="api-device-instance-detail-slash"),
    path("device-instances/<int:device_id>/provision", ProvisionDeviceView.as_view(), name="api-device-instance-provision"),
    path("device-instances/<int:device_id>/provision/", ProvisionDeviceView.as_view(), name="api-device-instance-provision-slash"),
    path("device-instances/control", DeviceControlView.as_view(), name="api-device-instance-control"),
    path("device-config/push-all", PushDeviceConfigAllView.as_view(), name="api-device-config-push-all"),
    path("device-config/test", TestApiHostView.as_view(), name="api-device-config-test"),
    path("ping", PingView.as_view(), name="api-ping"),
    path("ping/", PingView.as_view(), name="api-ping-slash"),
]


