# Generated by Django 5.2.9 on 2025-12-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rfidscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(blank=True, default='', max_length=128)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('api_host', models.CharField(blank=True, default='', max_length=256)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configuration',
            },
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('api_host', models.CharField(blank=True, default='', max_length=256)),
                ('ssid', models.CharField(blank=True, default='', max_length=128)),
                ('firmware', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
    ]
