# Generated by Django 5.2.9 on 2025-12-19 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deviceconfig_deviceinstance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstance',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceinstance',
            name='pairing_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
